### ISSUE TITLE
Can't access User Guide

### ISSUE THREAD

**Issue by jseadragon** [DavidGoodwin/virtual-planning-board#1]
When I try to access the User Guide or the main page, I get a popup that requires a login. Is this expected?

**Comment by DavidGoodwin** [comment]
see https://github.com/DavidGoodwin/virtual-planning-board/wiki ... I'm too stupid to figure out how to embed the images within it...

**Comment by DavidGoodwin** [comment]
Install guide is now in the wiki too...

**Comment by jseadragon** [comment]
> see https://github.com/DavidGoodwin/virtual-planning-board/wiki ... I'm too stupid to figure out how to embed the images within it...

Mind if I update the wiki with the embedded images?

**Comment by DavidGoodwin** [comment]
Hi - I've fixed the images ... but you're welcome to update the wiki if you so wish...
